### ISSUE TITLE
get nested mapping mistake

### ISSUE THREAD

**Issue by Rubiix** [nartc/automapper-nartc#2]
What if property of the db entity named "name".

You will get the error: 
Error: Mapping not found for source Blabla where is Blabla is the value of sourceEntity.name

The error in getNestedMapping method. What is the reason to take the name property?
 `val.name || val.constructor.name`

**Comment by exls** [comment]
Please, fix that!)

**Comment by nartc** [comment]
@Rubiix Thanks for reporting. I will look into that as soon as possible.

**Comment by nartc** [comment]
@Rubiix the main reason was there are two ways to get the class name at run time: `.name` or `.constructor.name` and this was written before I relied on `class-transformer`. Now with proper Decorator setup in your models, `.name` shouldn't be used because I run `plainToClass` in the beginning of the `map` method and that should instantiate all the nested models if setup properly which means `.constructor.name` should be available.

I'll push a fix soon.

cc @exls

**Comment by exls** [comment]
For now I use small trick, thanks mongoose for this feature
@Exclude()
class Account {
`@prop({
    trim: true,
    alias: 'exposedName',
  })
  name: string;
  // TODO: remove once automaper-nartc fixed
  @Expose()
  exposedName: string;`

and in profile

`this.createMap<Account, AccountVm>(
      Account,
      AccountVm,
    ).forMember('name', opts => opts.mapFrom(s => s.exposedName));`

**Comment by nartc** [comment]
@exls 🤦‍♂ man, my bad. I'll get that fixed ASAP
