### ISSUE TITLE
Mapping for source and destination already exist.

### ISSUE THREAD

**Issue by ofuochi** [nartc/automapper-nartc#3]
I have a test (mocha-chai) that runs in the background. After any file change, my server is restarted and everything is basically disposed at restart. However, I keep getting the error 

> Mapping for source XXX and destination XXXDto already exist.

This is a bit strange given that I restarted the whole server. Is there a method to call to dispose or unmap all mappings?

**Comment by exls** [comment]
Me too have same issue. Doesn't support same name. To solve right now use different class names. Not good, because in my module system project I have same class names. For example:

User->Metadata & Bank->Metadata. Of course different Metadata classes. Now I have to change class names to UserMetadata & BankMetadata. 

And you are right, for crud controllers I have same class names aka StoreDto, UpdateDto, etc

**Comment by nartc** [comment]
@ofuochi Thanks for reporting. I'll look into it as soon as possible.

**Comment by nartc** [comment]
@exls `User->Metadata & Bank->Metadata. Of course different Metadata classes. Now I have to change class names to UserMetadata & BankMetadata.` I'm not sure I follow this. You want to map from `Metadata` to `User` and `Metadata` to `Bank`? This should work. Mind elaborating a bit more? Thanks

**Comment by exls** [comment]
May be as a solution, add namespaces?
createMap(FromClass, ToClass, namespace = 'default namespace')

**Comment by nartc** [comment]
@exls you have a source repo that I can take a look at?

**Comment by nartc** [comment]
> May be as a solution, add namespaces?
> createMap(FromClass, ToClass, namespace = 'default namespace')

If you're talking about different namespaces, a better solution might be to allow the library consumer to instantiate the `AutoMapper` themselves instead of exporting a singleton from the library.
